spring:
  thymeleaf:
    mode: HTML5
    suffix: .html
    prefix: classpath:templates/
    check-template-location: true
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    web: DEBUG
